[package]
name = "selien"
version = "0.1.0"
edition = "2021"
description = "A ssot type-specification and generating tool."
repository = "https://github.com/March-mitsuki/selien"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "selien"
path = "src/main.rs"

[features]
wee_alloc = ["dep:wee_alloc"]

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
console_error_panic_hook = "0.1.7"
log = "0.4"
regex = "1.8.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
wasm-bindgen = "0.2.86"
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
assert_cmd = "2.0.11"
insta = { version = "1.29.0", features = ["yaml"] }
wasm-bindgen-test = "0.3.36"

[profile.dev.package.insta]
opt-level = 3

[profile.release]
# opt-level = "s"
debug = true
